version: '3'
services:
  jenkins: 
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      -  "8080:8080"
    volumes:
      -  "/home/syler/100daysofcodechallenge/jenkins-data/jenkins-udemy/jenkins-data/jenkins_home:/var/jenkins_home"
    networks:
      -  net
networks:
  net:
