kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: dStTtWKDvINlhPC3A58ZV2FycneQLyIsd+Hv0bGIEug=
      - identity: {}
